
package com.cts.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.cts.service.ObjectFactory;
import com.cts.service.Product;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProductService", targetNamespace = "http://service.cts.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProductService {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.cts.service.Product
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProductById", targetNamespace = "http://service.cts.com/", className = "com.cts.service.GetProductById")
    @ResponseWrapper(localName = "getProductByIdResponse", targetNamespace = "http://service.cts.com/", className = "com.cts.service.GetProductByIdResponse")
    @Action(input = "http://service.cts.com/ProductService/getProductByIdRequest", output = "http://service.cts.com/ProductService/getProductByIdResponse")
    public Product getProductById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
